// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzY3MYxybFKM3t65X_kkI09Q7D5KIz7xc',
    appId: '1:525682698625:web:f6b1a30b1f547ab258a080',
    messagingSenderId: '525682698625',
    projectId: 'codex-e3e06',
    authDomain: 'codex-e3e06.firebaseapp.com',
    storageBucket: 'codex-e3e06.firebasestorage.app',
    measurementId: 'G-047RG4NHK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbK8e5rjxL6a8O4Ntx9wFix6tFxILW6zk',
    appId: '1:525682698625:android:d0da7f26e7b1997158a080',
    messagingSenderId: '525682698625',
    projectId: 'codex-e3e06',
    storageBucket: 'codex-e3e06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx5azGhy_Kkr0WwSCGcobbYeZBnKJqx1g',
    appId: '1:525682698625:ios:54926c0ced1a9f3258a080',
    messagingSenderId: '525682698625',
    projectId: 'codex-e3e06',
    storageBucket: 'codex-e3e06.firebasestorage.app',
    iosBundleId: 'com.example.storySharingPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx5azGhy_Kkr0WwSCGcobbYeZBnKJqx1g',
    appId: '1:525682698625:ios:54926c0ced1a9f3258a080',
    messagingSenderId: '525682698625',
    projectId: 'codex-e3e06',
    storageBucket: 'codex-e3e06.firebasestorage.app',
    iosBundleId: 'com.example.storySharingPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzY3MYxybFKM3t65X_kkI09Q7D5KIz7xc',
    appId: '1:525682698625:web:31e0d1dddb1d856758a080',
    messagingSenderId: '525682698625',
    projectId: 'codex-e3e06',
    authDomain: 'codex-e3e06.firebaseapp.com',
    storageBucket: 'codex-e3e06.firebasestorage.app',
    measurementId: 'G-4PSSYNFKG1',
  );

}